runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /
  static_files: index.html
  upload: index.html
  login: required

- url: /proglist
  script: proglist.py
  login: required

- url: /proglist.ics
  script: proglist.py

- url: /proglist.opml
  script: proglist.py

- url: /static
  static_dir: static
